---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install -g mocha
  - npm install
  - bower install

script:
  - npm test
